# SPDX-License-Identifier: CC0-1.0
# Copyright (c) 2026 sol pbc

name = "welcome-mat"
account_id = "3f2c1528c7d4d9685819ea9e9e307c92"
compatibility_date = "2025-04-01"
main = "src/index.js"
routes = [{ pattern = "welcome-m.at", custom_domain = true }]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "welcome-mat-db"
database_id = "ff09b2d2-803c-47dc-a920-f577c030f0d9"
